---
- hosts: ios
  gather_facts: no


# {{ interface }} input  will be a survey in Ansible Tower


  tasks:
     - name: Verify VLAN
       ios_command:
         commands: 
           - show run int {{ interface }}          
       register: int

     - debug: var=int.stdout_lines   
        
